---
title: "Home advantage effect over players in Brazilian Soccer Championship"
author: "Rodrigo Volponi Leal"
date: "2014-09-22"
output:
  html_document:
    theme: cerulean
---

<!-- For more info on RMarkdown see http://rmarkdown.rstudio.com/ -->

<!-- Enter the code required to load your data in the space below. The data will be loaded but the line of code won't show up in your write up (echo=FALSE) in order to save space-->
```{r echo=FALSE}

```

<!-- In the remainder of the document, add R code chunks as needed -->

### Introduction:

In *Soccer*, there is a belief that is a significant advantage for a team to play in its own stadium, with support of its fan-base. Likewise, it would be a disadvantage to play in the opponent's field. 

This is known as "*Home Field Advantage*" ([Wikipedia article](http://en.wikipedia.org/wiki/Home_advantage)).

This project will explore the effect of the home field advantage in the overall performance of the players in Brazilian National Series A Championship of 2013.

*Research Question*
In Brazilian Soccer, playing in the "home field" effect the performance of the players?

### Data:

The data avaliable is from the 2013 Brazilian National Series A Championship of 2013 ([Wikipedia Campeonato Brasileiro Série A](http://en.wikipedia.org/wiki/Campeonato_Brasileiro_S%C3%A9rie_A)).

The player data, scouts and overall performance is avaliable at this project GitHub page:
https://github.com/volponi/coursera-dataanalysis-project/blob/master/2013_brazilian_championship_stats.csv


### Exploratory data analysis:

Insert exploratory data analysis here...

### Inference:

Insert inference section here...

### Conclusion:

Insert conclusion here...
